authors:
  john-berryman:
    name: John Berryman
    description: Founder of Arcturus Labs
    avatar: /assets/images/john_berryman_face.jpg
    social:
      twitter: JnBrymn
      linkedin: john-berryman-864b1713
    url: https://arcturus-labs.com/#about
