authors:
  john-berryman:
    name: John Berryman
    description: Founder of Arcturus Labs
    avatar: /assets/images/john_berryman_face.jpg
    social:
      twitter: JnBrymn
      linkedin: john-berryman-864b1713
    url: https://arcturus-labs.com/#about

  tobasum-mandal:
    name: Tobasum Mandal
    description: Vanderbilt
    avatar: /assets/images/tobasum_mandal.png
    social:
      linkedin: tobasum-mandal
    url: https://www.linkedin.com/in/tobasum-mandal
